#!/usr/bin/env python3
r"""Make a copy of sky130_fd_sc_hd.v that Icarus Verilog can use for SDF-annotated simulation.

Two things in the stock timing models defeat Icarus:

1. Sequential cells feed their UDP from `D_delayed`, `CLK_delayed`, `RESET_B_delayed`, ...
   wires that are driven only by $setuphold / $recrem "delayed signal" outputs. Icarus does not
   implement timing checks and leaves those wires undriven, so every flop outputs X.
   -> after each `wire X_delayed;` add `assign X_delayed = X;`

2. Their specify paths are edge-sensitive, e.g. `( posedge CLK => ( Q : CLK ) )`, but OpenSTA's
   write_sdf emits `(IOPATH CLK Q ...)` with no edge, and Icarus silently fails to match the two,
   so flops get zero clk->Q delay.
   -> rewrite `( posedge A => ( B : A ) )` as `( A => B )`

Result: IOPATH delays from the SDF are applied; setup/hold/recovery/width checks are NOT.
Usage: sky130_icarus_sdf_lib.py <pdk sky130_fd_sc_hd.v> <out.v>
"""
import re, sys

src, out = sys.argv[1:3]
delayed = re.compile(r"\s*wire\s+(\w+)_delayed\s*;")
edge = re.compile(r"\(\s*(?:posedge|negedge)\s+(\w+)\s*=>\s*\(\s*(\w+)\s*[:+\-]+\s*\w+\s*\)\s*\)")
n_wire = n_edge = 0
with open(src) as f, open(out, "w") as o:
    o.write("// Generated by scripts/sky130_icarus_sdf_lib.py from " + src + "\n")
    o.write("// Delays are applied; timing checks are not. See the script header.\n")
    for line in f:
        line, k = edge.subn(r"( \1 => \2 )", line)
        n_edge += k
        o.write(line)
        m = delayed.match(line)
        if m:
            o.write(f"    assign {m.group(1)}_delayed = {m.group(1)};\n")
            n_wire += 1
print(f"wrote {out}: {n_wire} delayed wires tied, {n_edge} specify paths made level-sensitive")
